Added RealmSwift, connectivity check to NetworkClient, loading animation and error text animation on login view
marinmarkelic/QuizApp pull request #39
Opened 2022-09-01 11:41 UTC by marinmarkelic

Added RealmSwift, loading animation and error text animation on login view.
Added connectivity check to NetworkClient.
Deleted unused UIKit components that i forgot to delete before.

https://user-images.githubusercontent.com/101728747/187904761-8b2dea13-6ab4-455d-aaa5-d8cfcda787fc.mp4

https://user-images.githubusercontent.com/101728747/187905478-75a4b70d-ccf5-4aee-a592-eac998f06f7b.MP4

https://user-images.githubusercontent.com/101728747/187905051-6fc06b06-941d-45e2-8e46-c0bcba3efe60.MP4

2022-09-01 11:45 UTC, marinmarkelic commented on QuizApp/QuizApp/DataSources/DataSourceModels.swift
> +    convenience init(_ model: QuizRepoModel) {
Im not sure where to move this since QuizDatabaseModel shouldn't be aware of QuizRepoModel

2022-09-01 12:10 UTC, marinmarkelic commented on QuizApp/QuizApp/DataSources/DataSourceModels.swift
> +    convenience init(_ model: QuizRepoModel) {
Nvm

2022-09-05 13:43 UTC, istaudacher requested changes

2022-09-05 13:43 UTC, istaudacher commented on QuizApp/QuizApp/DataSources/QuizDatabaseDataSource.swift
> +        guard let realm = try? Realm() else { return [] }
Create a class var `private let realm: Realm?` and assign a value to it on `init`. You can guard it here.

2022-09-05 13:43 UTC, istaudacher commented on QuizApp/QuizApp/DataSources/QuizDatabaseDataSource.swift
> +                if savedQuizzes.contains(where: {$0.id == quiz.id}) {
This can be a simple `if-let`.

2022-09-05 13:43 UTC, istaudacher commented on QuizApp/QuizApp/Network/Reachability.swift
> +            $0.withMemoryRebound(to: sockaddr.self, capacity: 1) {zeroSockAddress in
space after {

2022-09-05 13:43 UTC, istaudacher commented on QuizApp/QuizApp/Network/Reachability.swift
> +        if SCNetworkReachabilityGetFlags(defaultRouteReachability!, &flags) == false {
if !SCNetworkReachabilityGetFlags(defaultRouteReachability!, &flags)

2022-09-05 13:43 UTC, istaudacher commented on QuizApp/QuizApp/Network/Reachability.swift
> +        let ret = (isReachable && !needsConnection)
return isReachable && !needsConnection

2022-09-05 13:43 UTC, istaudacher commented on QuizApp/QuizApp/Repositories/QuizRepository.swift
> +                .fetchQuizzes()
Why can't DatabaseDS have `fetchQuizzes(for category)` and use filtering on DB level?

2022-09-05 15:30 UTC, istaudacher requested changes

2022-09-05 15:30 UTC, istaudacher commented on QuizApp/QuizApp/DataSources/QuizDatabaseDataSource.swift
> +                if let savedQuiz = savedQuizzes.first(where: {$0.id == quiz.id}) {
`savedQuizzes.first(where: { $0.id == quiz.id })`

2022-09-06 04:54 UTC, istaudacher approved these changes

2022-09-06 06:23 UTC, merged